export const SET_CURRENT_RECIPE = "SET_CURRENT_RECIPE";

export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";

export const SET_CURRENT_INGREDIENTS = "ADD_CURRENT_INGREDIENTS";
export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const SET_TAGS = "ADD_TAGS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CLEAR_CURRENT_RECIPE = "CLEAR_CURRENT_RECIPE";

